[package]
name = "synth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdev = "0.5.3"
rodio = "0.17.1"
coreaudio-sys = "0.2.13"

[[bin]]
name = "synth"
path = "src/main.rs"

[[bin]]
name = "bench"
path = "src/bench.rs"